### PR TITLE
Add formset:added and formset:removed events

### PR DESCRIPTION
**Pull request by leibowitz**
trigger [`formset:added`](https://github.com/django/django/blob/b9cf764be62e77b4777b3a75ec256f6209a57671/django/contrib/admin/static/admin/js/inlines.js#L126) and [`formset:removed`](https://github.com/django/django/blob/b9cf764be62e77b4777b3a75ec256f6209a57671/django/contrib/admin/static/admin/js/inlines.js#L103) events

### CODE REVIEW

**Comment by leibowitz** [comment]
@OskarPersson any chances to get that merged one day? It's really annoying that the django-nested-inline doesn't work well with any other plugin depending on formset:added and formset:removed events

**Comment by leibowitz** [comment]
not the only one that added (and depends) on this apparently:
https://github.com/Dmitri-Sintsov/django-nested-inline/commit/b0553beb82a2a46d1204e8849f188587d3e72083

**Comment by OskarPersson** [comment]
I know it's been a while since this PR was created (it was created before I became a maintainer of this repo!) but which tool did you use to minify the code? It's good to know going forward with other potential changes

**Comment by leibowitz** [comment]
Good question. It's been a while, but most likely [prettier](https://prettier.io/). I can try to re-generate it to compare

**Comment by OskarPersson** [comment]
Thanks!

**Pull request merged**
