### PR TITLE
Support Django 4.0

### LINKED ISSUE #135: Support Django 4.0
Features removed in 4.0: django.utils.encoding.force_text() are removed (admin.py, line 13)

### PR DESCRIPTION
**Pull request by Thorbenl**
Should close #135 :)

### CODE REVIEW

**Comment by OskarPersson** [comment]
I'd still like to support the old Django versions since it shouldn't be that much trouble. You should be able to do some conditional importing to still support both old and new versions.

**Comment by Thorbenl** [comment]
> I'd still like to support the old Django versions since it shouldn't be that much trouble. You should be able to do some conditional importing to still support both old and new versions.

@OskarPersson May I ask for your reasoning behind it? 3.2 Is the ne LTS, or rather will be in April, so it is not so far out, and according to the JetBrains survey, most people are using the newer versions anyway.
Screenshot 2022-01-07 at 09 40 42


Please let me know what you think :)

**Comment by OskarPersson** [comment]
My only reasoning is that it is still very easy to also support the old versions and therefore we should keep doing that.

**Comment by Thorbenl** [comment]
> My only reasoning is that it is still very easy to also support the old versions and therefore we should keep doing that.

@OskarPersson Very well :) I will revert the changes and re-add support of old versions

**Comment by Thorbenl** [comment]
@OskarPersson I have made the necessary changes now, let me know if you need anything more :')

**Comment by OskarPersson** [comment]
Please see the Python/Django version compatibility table to avoid incompatible versions: https://docs.djangoproject.com/en/4.0/faq/install/

(You'll have to check older versions of the documentation to see further back)

Also, you should maybe try to run this locally with tox and some virtualenvs instead of the trial and error strategy you seem to be using here ;)

**Comment by Thorbenl** [comment]
> Please see the Python/Django version compatibility table to avoid incompatible versions: https://docs.djangoproject.com/en/4.0/faq/install/
> 
> (You'll have to check older versions of the documentation to see further back)
> 
> Also, you should maybe try to run this locally with tox and some virtualenvs instead of the trial and error strategy you seem to be using here ;)

Sure :) I have run most of these now locally using `act`, and I seem to have no problem :D I think i got most of the important versions covered now. 

Sorry for this trial and error approach. It's the first time im contributing to a third party package. Thanks for your patience :)

**Comment by Thorbenl** [comment]
> Testing against main is a good idea but those jobs shouldn't be required to succeed in order for the PR to be mergable. If we want them included they should be optional

@OskarPersson very good idea. I dont want to hold this back any longer, since people are waiting for this. I will make a sep. PR including main and figuring out how we should make the CI checks not rely on it.

**Comment by OskarPersson** [comment]
Thanks!

**Pull request merged**
